---
title: "Investigating contaminants"
format: html
editor: visual
---

## Contaminants

```{r}
UCMRall <- read.csv("data/UCMR4_All.csv")
UCMRbystate <- read.csv("data/UCMR4_All_Tribes_AK_LA.csv", fileEncoding = "UTF-8")
```

```{r}
# finding the PWSs serving Indigenous pops
PWSs_state9 <- allUCMR %>% 
  filter(State == "9") %>% 
  select(PWSName) %>% 
  unique()

UCMR_CA_indig <- UCMRall %>% 
  filter(PWSName %in% c("Pala North", "Pauma", "Pechanga", "Redding Rancheria", 
                        "Viejas Community System") | State == "CA")

UCMR_CA_indig %>% 
  filter(is.na(AnalyticalResultValue.µg.L.) & AnalyticalResultsSign != "<")

UCMR_CA_indig %>% 
 # filter(!is.na(AnalyticalResultValue.microg.L.)) %>% 
  group_by(Contaminant) %>% 
  summarize(count = n())
```

It appears that all instances of NAs are as a result of the measurement being less than the minimum reporting level.

```{r}
UCMR_CA_indig <- UCMRbystate %>% 
  filter(PWSName %in% c("Pala North", "Pauma", "Pechanga", "Redding Rancheria", 
                        "Viejas Community System") | State == "CA")




allUCMR %>% 
  filter(PWSName %in% c("Pala North", "Pauma", "Pechanga", "Redding Rancheria", 
                        "Viejas Community System") | State == "CA") %>% 
  group_by(Contaminant) %>% 
  summarise(count = n())

## TRYING TO ID DISCREPANCIES BETWEEN BULK AND HALF

anti_join(UCMR_CA_indig2, UCMR_CA_indig, by = c("PWSID", "Contaminant"))

anti_join(UCMR_CA_indig, UCMR_CA_indig2, by = c("PWSID", "Contaminant"))

UCMR_CA_indig2 %>% 
  filter(PWSID == "CA1910005")

```

```{r}
library(dplyr)
library(ggplot2)
# install.packages("sf") # https://github.com/r-spatial/sf/issues/2035
library(sf)
library(tidycensus)
options(tigris_use_cache = TRUE)
library(tidyr)
library(purrr)
```

```{r}
# Checking which state has the most non-zero measurement values to work with

allUCMR_wValues <- allUCMR %>% 
  filter(!is.na(AnalyticalResultValue.µg.L.) & AnalyticalResultValue.µg.L. != 0)

allUCMR_wValues %>% 
  group_by(State) %>% 
  summarize(NumMeasurements = length(AnalyticalResultValue.µg.L.)) %>% 
  arrange(desc(NumMeasurements))

allUCMR_wValues %>% 
  filter(State == "CA") %>% 
  group_by(Contaminant) %>% 
  summarize(NumMeasurementsByContam = length(AnalyticalResultValue.µg.L.)) %>% 
  arrange(desc(NumMeasurementsByContam))
  
```

```{r}
# Checking which state has the most non-zero, non-HAA# measurement values to work with
# Since the HAAs are monitored by the EPA

allUCMR_wValues_noHAA <- allUCMR %>% 
  filter(!is.na(AnalyticalResultValue.µg.L.) & AnalyticalResultValue.µg.L. != 0
         & !Contaminant %in% c("HAA9", "HAA5", "HAA6Br"))

allUCMR_wValues_noHAA %>% 
  group_by(State) %>% 
  summarize(NumMeasurements = length(AnalyticalResultValue.µg.L.)) %>% 
  arrange(desc(NumMeasurements))

allUCMR_wValues_noHAA %>% 
  filter(State == "CA") %>% 
  group_by(Contaminant) %>% 
  summarize(NumMeasurementsByContam = length(AnalyticalResultValue.µg.L.)) %>% 
  arrange(desc(NumMeasurementsByContam))
```

```{r}
# Checking which contaminant in CA has the most non-NA measurement values to work with

allUCMR_nonNA <- allUCMR %>% 
  filter(!is.na(AnalyticalResultValue.µg.L.))

allUCMR_wValues %>% 
  group_by(State) %>% 
  summarize(NumMeasurements = length(AnalyticalResultValue.µg.L.)) %>% 
  arrange(desc(NumMeasurements))

allUCMR_wValues %>% 
  filter(State == "CA") %>% 
  group_by(Contaminant) %>% 
  summarize(NumMeasurementsByContam = length(AnalyticalResultValue.µg.L.)) %>% 
  arrange(desc(NumMeasurementsByContam))

allUCMR_nonNA %>% 
  filter(State == "CA") %>% 
  group_by(Contaminant) %>% 
  summarize(NumMeasurementsByContam = length(AnalyticalResultValue.µg.L.)) %>% 
  arrange(desc(NumMeasurementsByContam))
  
```

```{r}
UCMR_CA <- allUCMR %>% 
  filter(State == "CA")
```

```{r}
UCMR %>% 
  filter(!is.na(AnalyticalResultValue.µg.L.) & AnalyticalResultValue.µg.L. != 0) %>% 
  filter(Contaminant %in% c("manganese", "germanium", "HAA9", "HAA6Br")) %>% 
  group_by(Contaminant) %>% 
  summarize(count = n()) %>% 
  arrange(count)
```
